### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by TiszaAdam**
Using dotCover's code coverage statistics to implement better unit tests

### CODE REVIEW

**Comment by TiszaAdam** [comment]
Code coverage before new tests
TestCoverage before new tests

**Comment by TiszaAdam** [comment]
First implemented tests for QueryResult serializing, queries with filter, and MemoryStore serializing.

Code coverage after new tests:

TestCoverage after 3rd new test

**Comment by TiszaAdam** [comment]
Then implemented Graph serializing into turtle format
a922c541aa1697c182524424b877ee9848436b49

Code coverage after new test:

TestCoverage after 4th new test

**Comment by kristof12345** [comment]
A Travis nem tudta buildelni, és a Codacy szerint a kódminőség sem megfelelő, ha ezeket javítod, akkor majd tudjuk mergelni.

**Pull request merged**
